version: '3.3'
services:
  lb-haproxy:
    build:
      context: .
      dockerfile: Dockerfile-haproxy
    ports:
      - '80:80'
      - '8181:8181'
    hostname: lb-haproxy.local
    depends_on:
      - liferay-portal-node-1
      - liferay-portal-node-2
  liferay-portal-node-1:
    build:
      context: .
      dockerfile: Dockerfile-liferay
    ports:
      - '6080:8080'
      - '21311:11311'
    hostname: liferay-portal-node-1.local
    volumes:
      - lfr-dl-volume:/data/liferay/document_library
    depends_on:
      - postgres
      - es-node-1
      - es-node-2
  liferay-portal-node-2:
    build:
      context: .
      dockerfile: Dockerfile-liferay
    ports:
      - '7080:8080'
      - '31311:11311'
    hostname: liferay-portal-node-2.local
    volumes:
      - lfr-dl-volume:/data/liferay/document_library
    depends_on:
      - postgres
      - liferay-portal-node-1
      - es-node-1
      - es-node-2
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=my-secret-pw
      - POSTGRES_USER=liferay
      - POSTGRES_DB=lportal
  es-node-1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.4
    environment:
      - cluster.name=docker-elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  es-node-2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.4
    environment:
      - cluster.name=docker-elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=es-node-1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    volumes:
      - esdata2:/usr/share/elasticsearch/data
volumes:
  lfr-dl-volume:
  esdata1:
  esdata2:
